### ISSUE TITLE
Demeteorizer v3.0.0 & Meteor v1.2 Compatibility

### ISSUE THREAD

**Issue by boustanihani** [CleverCloud/demo-meteorjs#5]
The `install.sh` script seems no longer compatible with Demeteorizer v3.0.0 & Meteor v1.2

I am getting the error `TypeError: Object [object Object] has no method 'npmRequire'`` so it also seems to be related to: https://github.com/meteorhacks/npm

Still haven't figured out how to fix, hope someone could help :)

**Comment by BlackYoup** [comment]
Hi,

I've just updated the build setup, can you check and tell me if it fixes your issue ?

**Comment by boustanihani** [comment]
Thanks, I just managed to deploy after taking a look at the changes you made :sunglasses:

Just hope Clever-Cloud would allow us to create a meteor deployment environment (app) in the backend and simply push our code to it... I mean official meteor support where such changes take place in the background :bowtie:

**Comment by BlackYoup** [comment]
That's something we will discuss, glad to see it fixes your issues and thanks for the report :)
